# EDGAR - The SEC's Electronic Data Gathering, Analysis, and Retrieval (EDGAR) system

There are a lot of EDGAR-related endpoints at https://www.sec.gov.  Most of the EDGAR overview can be found through [the link to search public filings](https://www.sec.gov/search-filings).  The EDGAR search itself is available at https://www.sec.gov/edgar/search/.  There is a good amount of additional info in the [FAQ](https://www.sec.gov/edgar/search/efts-faq.html), the [API documentation](https://www.sec.gov/search-filings/edgar-application-programming-interfaces), and the [data resources](https://www.sec.gov/data-research/sec-data-resources).

### Open government data in general

Slightly off-topic here, but there are a lot of additional open datasets at https://data.gov/open-gov/.

## Imports

In [110]:
import requests
import json
from io import StringIO
import datetime
import pandas as pd

## Headers

According to the [developer FAQ](https://www.sec.gov/about/webmaster-frequently-asked-questions#developers), you must declare your identity in the `User-Agent` header.

In [79]:
with open('../../../../../.config/edgar/user-agent', 'r') as file:
    user_agent = file.read().strip()
headers = {
    'User-Agent': user_agent
}

## CIK data

EDGAR's Central Index Key (CIK) is the uuid used to track filing registered by a particular entity.  There is a large list of these downloadable at https://www.sec.gov/Archives/edgar/cik-lookup-data.txt .

There are alernative (possibly old/out-dated) mappings by ticker https://www.sec.gov/files/company_tickers.json and by ticket and exchange https://www.sec.gov/files/company_tickers_exchange.json .

### All CIK data

In [4]:
# Todo - parse the txt data at ../../data/edgar/all_cik_data.txt

### CIK by ticker

In [5]:
cik_ticker = pd.read_json('../../data/edgar/company_tickers.json')
cik_ticker = cik_ticker.transpose()
cik_ticker

       cik_str ticker                                    title
0      1045810   NVDA                              NVIDIA CORP
1       320193   AAPL                               Apple Inc.
2      1652044  GOOGL                            Alphabet Inc.
3       789019   MSFT                           MICROSOFT CORP
4      1018724   AMZN                           AMAZON COM INC
...        ...    ...                                      ...
10420  2086264  VHCPU    Vine Hill Capital Investment Corp. II
10421  2097364  TMTSU           Spartacus Acquisition Corp. II
10422  2107960  SWCPF                            SWCC Corp/ADR
10423  2093654  ZJNGF  Zijin Gold International Co Limited/ADR
10424  2093667  MAWAF                     Maruwa Co., Ltd./ADR

[10425 rows x 3 columns]

#### Test of $MSFT CIK lookup

In [6]:
msft_cik_ticker = cik_ticker[cik_ticker['ticker'] == 'MSFT']
print(msft_cik_ticker)
print("Extracted MSFT CIK: ", msft_cik_ticker['cik_str'].iloc[0])

  cik_str ticker           title
3  789019   MSFT  MICROSOFT CORP
Extracted MSFT CIK:  789019

### CIK by ticker _and_ exchange

#### Reformat the JSON to the form expected by pandas.read_json

In [7]:
def create_cik_exchange_json(filepath: str) -> str:
    """
    Formats the input company_tickers_exchange.json file to the form expected by pandas.read_json().
    """
    with open(filepath, 'r') as file:
        text = file.read().strip()
    cik_exchange = json.loads(text)
    assert validate_cik_exchange_data(cik_exchange['data'])
    return convert_cik_exchange_data_to_json(cik_exchange)

def validate_cik_exchange_data(data: dict, length: int=4) -> bool:
    """
    Validates that the input array of items in the CIK breakdown by ticker and exchange.
    """
    for item in data:
        if len(item) != length:
            print("Invalid length: ", item)
            return False
    return True

def convert_cik_exchange_data_to_json(unformatted_data: dict) -> str:
    """
    Converts the dict-ified version of the company_tickers_exchange.json data into a JSON string compatible with pandas.read_json().
    """
    fields = unformatted_data['fields']
    formatted = {}
    index = 0
    for item in unformatted_data['data']:
        formatted_item = {}
        for column in range(len(fields)):
            formatted_item[fields[column]] = item[column]
        formatted[index] = formatted_item
        index += 1
    return json.dumps(formatted)

#### Read in the CIK data labeled by ticker _and_ exchange

In [8]:
cik_ticker_exchange_json = create_cik_exchange_json('../../data/edgar/company_tickers_exchange.json')
cik_ticker_exchange = pd.read_json(StringIO(cik_ticker_exchange_json))  # raw string is deprecated
cik_ticker_exchange = cik_ticker_exchange.transpose()
cik_ticker_exchange

           cik                                   name ticker exchange
0      1045810                            NVIDIA CORP   NVDA   Nasdaq
1       320193                             Apple Inc.   AAPL   Nasdaq
2      1652044                          Alphabet Inc.  GOOGL   Nasdaq
3       789019                         MICROSOFT CORP   MSFT   Nasdaq
4      1018724                         AMAZON COM INC   AMZN   Nasdaq
...        ...                                    ...    ...      ...
10407  2108124  Odakyu Electric Railway Co., Ltd./ADR  ODERF      OTC
10408  2108180                    NOF Corporation/ADR  NOFCF      OTC
10409  2108185                  Azbil Corporation/ADR  YMATF      OTC
10410  2109234                  BELIMO Holding AG/ADR  BLHWF      OTC
10411  2109556                 Minimax Group Inc./ADR  MNMXF      OTC

[10412 rows x 4 columns]

#### Test of $MSFT CIK lookup

In [9]:
msft_cik_ticker_exchange = cik_ticker_exchange[cik_ticker_exchange['ticker'] == 'MSFT']
print(msft_cik_ticker_exchange)
print("Extracted CIK: ", msft_cik_ticker_exchange['cik'].iloc[0])

      cik            name ticker exchange
3  789019  MICROSOFT CORP   MSFT   Nasdaq
Extracted CIK:  789019

## Company filing data

I'm still figuring out the ideal endpoint, but it looks like `https://data.sec.gov/api/xbrl/companyfacts/CIK<cik_str>.json` is the endpoint for getting all data.  There are additional references to bulk zip files:
- https://www.sec.gov/Archives/edgar/daily-index/xbrl/companyfacts.zip
- https://www.sec.gov/Archives/edgar/daily-index/bulkdata/submissions.zip

Again, I'm not sure which is the better to use.

### Padding CIKs

CIKs are meant to be 10-digit unique IDs.  Nevertheless, EDGAR's own data excludes the leading 0s.  The function(s) below pad the front of an input CIK with 0s.

In [46]:
def pad_cik(cik: str | int) -> str:
    """
    Adds leading 0s to a CIK.
    """
    cik = str(cik)
    if len(cik) < 10:
        padding = 10 - len(cik)
        cik = ('0' * padding) + cik
    return cik

### $MSFT filing lookup

In [48]:
msft_cik = msft_cik_ticker_exchange['cik'].iloc[0]
msft_cik = pad_cik(msft_cik)
msft_url = f"https://data.sec.gov/api/xbrl/companyfacts/CIK{msft_cik}.json"

response = requests.get(msft_url, headers=headers)

In [49]:
response.status_code

200

#### Share history

I wanted to see how fine-grained the data here was, and how far back it went.  There are several keys related to shares outstanding and share repurchases, but they seem to only go back to 2007.  The filings themselves don't seem to go back before 2010, somehow -- these appear to be corrected filings.

**Todo** - I should see if this is unique to $MSFT or if this is a general problem with the endpoint data.  Maybe this isn't an issue with the bulk zip data...

In [134]:
msft_facts = response.json()

# Interesting keys:
# facts: {dei: {}, us-gaap: {}}
# dei: {EntityCommonStockSharesOutstanding}
# us-gaap: {StockRepurchasedDuringPeriodShares}
# us-gaap: {CommonStockSharesOutstanding}
# us-gaap: {WeightedAverageNumberOfSharesOutstandingBasic}
# us-gaap: {WeightedAverageNumberOfDilutedSharesOutstanding}
# us-gaap: {PaymentsForRepurchaseOfCommonStock}
# us-gaap: {StockRepurchasedDuringPeriodShares}
# us-gaap: {StockRepurchasedDuringPeriodValue}

for item in msft_facts['facts']['us-gaap']['StockRepurchasedDuringPeriodShares']['units']['shares']:
    print(item)

{'start': '2007-07-01', 'end': '2007-09-30', 'val': 81000000, 'accn': '0001193125-10-171791', 'fy': 2010, 'fp': 'FY', 'form': '10-K', 'filed': '2010-07-30', 'frame': 'CY2007Q3'}
{'start': '2007-10-01', 'end': '2007-12-31', 'val': 120000000, 'accn': '0001193125-10-171791', 'fy': 2010, 'fp': 'FY', 'form': '10-K', 'filed': '2010-07-30', 'frame': 'CY2007Q4'}
{'start': '2008-01-01', 'end': '2008-03-31', 'val': 30000000, 'accn': '0001193125-10-171791', 'fy': 2010, 'fp': 'FY', 'form': '10-K', 'filed': '2010-07-30', 'frame': 'CY2008Q1'}
{'start': '2007-07-01', 'end': '2008-06-30', 'val': 402000000, 'accn': '0001193125-10-171791', 'fy': 2010, 'fp': 'FY', 'form': '10-K', 'filed': '2010-07-30', 'frame': 'CY2008'}
{'start': '2008-04-01', 'end': '2008-06-30', 'val': 171000000, 'accn': '0001193125-10-171791', 'fy': 2010, 'fp': 'FY', 'form': '10-K', 'filed': '2010-07-30', 'frame': 'CY2008Q2'}
{'start': '2008-07-01', 'end': '2008-09-30', 'val': 223000000, 'accn': '0001193125-10-171791', 'fy': 2010, 'fp': 'FY', 'form': '10-K', 'filed': '2010-07-30'}
{'start': '2008-07-01', 'end': '2008-09-30', 'val': 223000000, 'accn': '0001193125-11-200680', 'fy': 2011, 'fp': 'FY', 'form': '10-K', 'filed': '2011-07-28', 'frame': 'CY2008Q3'}
{'start': '2008-10-01', 'end': '2008-12-31', 'val': 95000000, 'accn': '0001193125-10-171791', 'fy': 2010, 'fp': 'FY', 'form': '10-K', 'filed': '2010-07-30'}
{'start': '2008-10-01', 'end': '2008-12-31', 'val': 95000000, 'accn': '0001193125-11-200680', 'fy': 2011, 'fp': 'FY', 'form': '10-K', 'filed': '2011-07-28', 'frame': 'CY2008Q4'}
{'start': '2009-01-01', 'end': '2009-03-31', 'val': 0, 'accn': '0001193125-10-171791', 'fy': 2010, 'fp': 'FY', 'form': '10-K', 'filed': '2010-07-30'}
{'start': '2009-01-01', 'end': '2009-03-31', 'val': 0, 'accn': '0001193125-11-200680', 'fy': 2011, 'fp': 'FY', 'form': '10-K', 'filed': '2011-07-28', 'frame': 'CY2009Q1'}
{'start': '2008-07-01', 'end': '2009-06-30', 'val': 318000000, 'accn': '0001193125-10-171791', 'fy': 2010, 'fp': 'FY', 'form': '10-K', 'filed': '2010-07-30'}
{'start': '2008-07-01', 'end': '2009-06-30', 'val': 318000000, 'accn': '0001193125-11-200680', 'fy': 2011, 'fp': 'FY', 'form': '10-K', 'filed': '2011-07-28', 'frame': 'CY2009'}
{'start': '2009-04-01', 'end': '2009-06-30', 'val': 0, 'accn': '0001193125-10-171791', 'fy': 2010, 'fp': 'FY', 'form': '10-K', 'filed': '2010-07-30'}
{'start': '2009-04-01', 'end': '2009-06-30', 'val': 0, 'accn': '0001193125-11-200680', 'fy': 2011, 'fp': 'FY', 'form': '10-K', 'filed': '2011-07-28', 'frame': 'CY2009Q2'}
{'start': '2009-07-01', 'end': '2009-09-30', 'val': 58000000, 'accn': '0001193125-10-171791', 'fy': 2010, 'fp': 'FY', 'form': '10-K', 'filed': '2010-07-30'}
{'start': '2009-07-01', 'end': '2009-09-30', 'val': 58000000, 'accn': '0001193125-10-239825', 'fy': 2011, 'fp': 'Q1', 'form': '10-Q', 'filed': '2010-10-28'}
{'start': '2009-07-01', 'end': '2009-09-30', 'val': 58000000, 'accn': '0001193125-11-200680', 'fy': 2011, 'fp': 'FY', 'form': '10-K', 'filed': '2011-07-28'}
{'start': '2009-07-01', 'end': '2009-09-30', 'val': 58000000, 'accn': '0001193125-12-316848', 'fy': 2012, 'fp': 'FY', 'form': '10-K', 'filed': '2012-07-26', 'frame': 'CY2009Q3'}
{'start': '2009-07-01', 'end': '2009-12-31', 'val': 183000000, 'accn': '0001193125-11-015947', 'fy': 2011, 'fp': 'Q2', 'form': '10-Q', 'filed': '2011-01-27'}
{'start': '2009-10-01', 'end': '2009-12-31', 'val': 125000000, 'accn': '0001193125-10-171791', 'fy': 2010, 'fp': 'FY', 'form': '10-K', 'filed': '2010-07-30'}
{'start': '2009-10-01', 'end': '2009-12-31', 'val': 125000000, 'accn': '0001193125-11-015947', 'fy': 2011, 'fp': 'Q2', 'form': '10-Q', 'filed': '2011-01-27'}
{'start': '2009-10-01', 'end': '2009-12-31', 'val': 125000000, 'accn': '0001193125-11-200680', 'fy': 2011, 'fp': 'FY', 'form': '10-K', 'filed': '2011-07-28'}
{'start': '2009-10-01', 'end': '2009-12-31', 'val': 125000000, 'accn': '0001193125-12-316848', 'fy': 2012, 'fp': 'FY', 'form': '10-K', 'filed': '2012-07-26', 'frame': 'CY2009Q4'}
{'start': '2009-07-01', 'end': '2010-03-31', 'val': 250000000, 'accn': '0001193125-11-115186', 'fy': 2011, 'fp': 'Q3', 'form': '10-Q', 'filed': '2011-04-28'}
{'start': '2010-01-01', 'end': '2010-03-31', 'val': 67000000, 'accn': '0001193125-10-171791', 'fy': 2010, 'fp': 'FY', 'form': '10-K', 'filed': '2010-07-30'}
{'start': '2010-01-01', 'end': '2010-03-31', 'val': 67000000, 'accn': '0001193125-11-115186', 'fy': 2011, 'fp': 'Q3', 'form': '10-Q', 'filed': '2011-04-28'}
{'start': '2010-01-01', 'end': '2010-03-31', 'val': 67000000, 'accn': '0001193125-11-200680', 'fy': 2011, 'fp': 'FY', 'form': '10-K', 'filed': '2011-07-28'}
{'start': '2010-01-01', 'end': '2010-03-31', 'val': 67000000, 'accn': '0001193125-12-316848', 'fy': 2012, 'fp': 'FY', 'form': '10-K', 'filed': '2012-07-26', 'frame': 'CY2010Q1'}
{'start': '2009-07-01', 'end': '2010-06-30', 'val': 380000000, 'accn': '0001193125-10-171791', 'fy': 2010, 'fp': 'FY', 'form': '10-K', 'filed': '2010-07-30'}
{'start': '2009-07-01', 'end': '2010-06-30', 'val': 380000000, 'accn': '0001193125-11-200680', 'fy': 2011, 'fp': 'FY', 'form': '10-K', 'filed': '2011-07-28'}
{'start': '2009-07-01', 'end': '2010-06-30', 'val': 380000000, 'accn': '0001193125-12-316848', 'fy': 2012, 'fp': 'FY', 'form': '10-K', 'filed': '2012-07-26', 'frame': 'CY2010'}
{'start': '2010-04-01', 'end': '2010-06-30', 'val': 130000000, 'accn': '0001193125-10-171791', 'fy': 2010, 'fp': 'FY', 'form': '10-K', 'filed': '2010-07-30'}
{'start': '2010-04-01', 'end': '2010-06-30', 'val': 130000000, 'accn': '0001193125-11-200680', 'fy': 2011, 'fp': 'FY', 'form': '10-K', 'filed': '2011-07-28'}
{'start': '2010-04-01', 'end': '2010-06-30', 'val': 130000000, 'accn': '0001193125-12-316848', 'fy': 2012, 'fp': 'FY', 'form': '10-K', 'filed': '2012-07-26', 'frame': 'CY2010Q2'}
{'start': '2010-07-01', 'end': '2010-09-30', 'val': 163000000, 'accn': '0001193125-10-239825', 'fy': 2011, 'fp': 'Q1', 'form': '10-Q', 'filed': '2010-10-28'}
{'start': '2010-07-01', 'end': '2010-09-30', 'val': 163000000, 'accn': '0001193125-11-200680', 'fy': 2011, 'fp': 'FY', 'form': '10-K', 'filed': '2011-07-28'}
{'start': '2010-07-01', 'end': '2010-09-30', 'val': 163000000, 'accn': '0001193125-11-276022', 'fy': 2012, 'fp': 'Q1', 'form': '10-Q', 'filed': '2011-10-20'}
{'start': '2010-07-01', 'end': '2010-09-30', 'val': 163000000, 'accn': '0001193125-12-316848', 'fy': 2012, 'fp': 'FY', 'form': '10-K', 'filed': '2012-07-26', 'frame': 'CY2010Q3'}
{'start': '2010-07-01', 'end': '2010-12-31', 'val': 351000000, 'accn': '0001193125-11-015947', 'fy': 2011, 'fp': 'Q2', 'form': '10-Q', 'filed': '2011-01-27'}
{'start': '2010-07-01', 'end': '2010-12-31', 'val': 351000000, 'accn': '0001193125-12-026864', 'fy': 2012, 'fp': 'Q2', 'form': '10-Q/A', 'filed': '2012-01-27'}
{'start': '2010-10-01', 'end': '2010-12-31', 'val': 188000000, 'accn': '0001193125-11-015947', 'fy': 2011, 'fp': 'Q2', 'form': '10-Q', 'filed': '2011-01-27'}
{'start': '2010-10-01', 'end': '2010-12-31', 'val': 188000000, 'accn': '0001193125-11-200680', 'fy': 2011, 'fp': 'FY', 'form': '10-K', 'filed': '2011-07-28'}
{'start': '2010-10-01', 'end': '2010-12-31', 'val': 188000000, 'accn': '0001193125-12-026864', 'fy': 2012, 'fp': 'Q2', 'form': '10-Q/A', 'filed': '2012-01-27'}
{'start': '2010-10-01', 'end': '2010-12-31', 'val': 188000000, 'accn': '0001193125-12-316848', 'fy': 2012, 'fp': 'FY', 'form': '10-K', 'filed': '2012-07-26', 'frame': 'CY2010Q4'}
{'start': '2010-07-01', 'end': '2011-03-31', 'val': 381000000, 'accn': '0001193125-11-115186', 'fy': 2011, 'fp': 'Q3', 'form': '10-Q', 'filed': '2011-04-28'}
{'start': '2010-07-01', 'end': '2011-03-31', 'val': 381000000, 'accn': '0001193125-12-170665', 'fy': 2012, 'fp': 'Q3', 'form': '10-Q', 'filed': '2012-04-19'}
{'start': '2011-01-01', 'end': '2011-03-31', 'val': 30000000, 'accn': '0001193125-11-115186', 'fy': 2011, 'fp': 'Q3', 'form': '10-Q', 'filed': '2011-04-28'}
{'start': '2011-01-01', 'end': '2011-03-31', 'val': 30000000, 'accn': '0001193125-11-200680', 'fy': 2011, 'fp': 'FY', 'form': '10-K', 'filed': '2011-07-28'}
{'start': '2011-01-01', 'end': '2011-03-31', 'val': 30000000, 'accn': '0001193125-12-170665', 'fy': 2012, 'fp': 'Q3', 'form': '10-Q', 'filed': '2012-04-19'}
{'start': '2011-01-01', 'end': '2011-03-31', 'val': 30000000, 'accn': '0001193125-12-316848', 'fy': 2012, 'fp': 'FY', 'form': '10-K', 'filed': '2012-07-26', 'frame': 'CY2011Q1'}
{'start': '2010-07-01', 'end': '2011-06-30', 'val': 447000000, 'accn': '0001193125-11-200680', 'fy': 2011, 'fp': 'FY', 'form': '10-K', 'filed': '2011-07-28'}
{'start': '2010-07-01', 'end': '2011-06-30', 'val': 447000000, 'accn': '0001193125-12-316848', 'fy': 2012, 'fp': 'FY', 'form': '10-K', 'filed': '2012-07-26'}
{'start': '2010-07-01', 'end': '2011-06-30', 'val': 447000000, 'accn': '0001193125-13-310206', 'fy': 2013, 'fp': 'FY', 'form': '10-K', 'filed': '2013-07-30'}
{'start': '2010-07-01', 'end': '2011-06-30', 'val': 447000000, 'accn': '0001193125-13-455144', 'fy': 2013, 'fp': 'FY', 'form': '8-K', 'filed': '2013-11-26', 'frame': 'CY2011'}
{'start': '2011-04-01', 'end': '2011-06-30', 'val': 66000000, 'accn': '0001193125-11-200680', 'fy': 2011, 'fp': 'FY', 'form': '10-K', 'filed': '2011-07-28'}
{'start': '2011-04-01', 'end': '2011-06-30', 'val': 66000000, 'accn': '0001193125-12-316848', 'fy': 2012, 'fp': 'FY', 'form': '10-K', 'filed': '2012-07-26', 'frame': 'CY2011Q2'}
{'start': '2011-07-01', 'end': '2011-09-30', 'val': 38000000, 'accn': '0001193125-11-276022', 'fy': 2012, 'fp': 'Q1', 'form': '10-Q', 'filed': '2011-10-20'}
{'start': '2011-07-01', 'end': '2011-09-30', 'val': 38000000, 'accn': '0001193125-12-316848', 'fy': 2012, 'fp': 'FY', 'form': '10-K', 'filed': '2012-07-26'}
{'start': '2011-07-01', 'end': '2011-09-30', 'val': 38000000, 'accn': '0001193125-12-427209', 'fy': 2013, 'fp': 'Q1', 'form': '10-Q', 'filed': '2012-10-18', 'frame': 'CY2011Q3'}
{'start': '2011-07-01', 'end': '2011-12-31', 'val': 78000000, 'accn': '0001193125-12-026864', 'fy': 2012, 'fp': 'Q2', 'form': '10-Q/A', 'filed': '2012-01-27'}
{'start': '2011-10-01', 'end': '2011-12-31', 'val': 39000000, 'accn': '0001193125-12-026864', 'fy': 2012, 'fp': 'Q2', 'form': '10-Q/A', 'filed': '2012-01-27'}
{'start': '2011-10-01', 'end': '2011-12-31', 'val': 39000000, 'accn': '0001193125-12-316848', 'fy': 2012, 'fp': 'FY', 'form': '10-K', 'filed': '2012-07-26', 'frame': 'CY2011Q4'}
{'start': '2011-07-01', 'end': '2012-03-31', 'val': 109000000, 'accn': '0001193125-12-170665', 'fy': 2012, 'fp': 'Q3', 'form': '10-Q', 'filed': '2012-04-19'}
{'start': '2012-01-01', 'end': '2012-03-31', 'val': 31000000, 'accn': '0001193125-12-170665', 'fy': 2012, 'fp': 'Q3', 'form': '10-Q', 'filed': '2012-04-19'}
{'start': '2012-01-01', 'end': '2012-03-31', 'val': 31000000, 'accn': '0001193125-12-316848', 'fy': 2012, 'fp': 'FY', 'form': '10-K', 'filed': '2012-07-26', 'frame': 'CY2012Q1'}
{'start': '2011-07-01', 'end': '2012-06-30', 'val': 142000000, 'accn': '0001193125-12-316848', 'fy': 2012, 'fp': 'FY', 'form': '10-K', 'filed': '2012-07-26'}
{'start': '2011-07-01', 'end': '2012-06-30', 'val': 142000000, 'accn': '0001193125-13-310206', 'fy': 2013, 'fp': 'FY', 'form': '10-K', 'filed': '2013-07-30'}
{'start': '2011-07-01', 'end': '2012-06-30', 'val': 142000000, 'accn': '0001193125-13-455144', 'fy': 2013, 'fp': 'FY', 'form': '8-K', 'filed': '2013-11-26'}
{'start': '2011-07-01', 'end': '2012-06-30', 'val': 142000000, 'accn': '0001193125-14-289961', 'fy': 2014, 'fp': 'FY', 'form': '10-K', 'filed': '2014-07-31', 'frame': 'CY2012'}
{'start': '2012-04-01', 'end': '2012-06-30', 'val': 34000000, 'accn': '0001193125-12-316848', 'fy': 2012, 'fp': 'FY', 'form': '10-K', 'filed': '2012-07-26', 'frame': 'CY2012Q2'}
{'start': '2012-07-01', 'end': '2012-09-30', 'val': 33000000, 'accn': '0001193125-12-427209', 'fy': 2013, 'fp': 'Q1', 'form': '10-Q', 'filed': '2012-10-18', 'frame': 'CY2012Q3'}
{'start': '2012-07-01', 'end': '2013-06-30', 'val': 158000000, 'accn': '0001193125-13-310206', 'fy': 2013, 'fp': 'FY', 'form': '10-K', 'filed': '2013-07-30'}
{'start': '2012-07-01', 'end': '2013-06-30', 'val': 158000000, 'accn': '0001193125-13-455144', 'fy': 2013, 'fp': 'FY', 'form': '8-K', 'filed': '2013-11-26'}
{'start': '2012-07-01', 'end': '2013-06-30', 'val': 158000000, 'accn': '0001193125-14-289961', 'fy': 2014, 'fp': 'FY', 'form': '10-K', 'filed': '2014-07-31'}
{'start': '2012-07-01', 'end': '2013-06-30', 'val': 158000000, 'accn': '0001193125-15-272806', 'fy': 2015, 'fp': 'FY', 'form': '10-K', 'filed': '2015-07-31'}
{'start': '2012-07-01', 'end': '2013-06-30', 'val': 158000000, 'accn': '0001193125-15-353706', 'fy': None, 'fp': None, 'form': '8-K', 'filed': '2015-10-27', 'frame': 'CY2013'}
{'start': '2013-07-01', 'end': '2013-09-30', 'val': 47000000, 'accn': '0001193125-16-662209', 'fy': 2016, 'fp': 'FY', 'form': '10-K', 'filed': '2016-07-28', 'frame': 'CY2013Q3'}
{'start': '2013-10-01', 'end': '2013-12-31', 'val': 53000000, 'accn': '0001193125-16-662209', 'fy': 2016, 'fp': 'FY', 'form': '10-K', 'filed': '2016-07-28', 'frame': 'CY2013Q4'}
{'start': '2014-01-01', 'end': '2014-03-31', 'val': 47000000, 'accn': '0001193125-16-662209', 'fy': 2016, 'fp': 'FY', 'form': '10-K', 'filed': '2016-07-28', 'frame': 'CY2014Q1'}
{'start': '2013-07-01', 'end': '2014-06-30', 'val': 175000000, 'accn': '0001193125-14-289961', 'fy': 2014, 'fp': 'FY', 'form': '10-K', 'filed': '2014-07-31'}
{'start': '2013-07-01', 'end': '2014-06-30', 'val': 175000000, 'accn': '0001193125-15-272806', 'fy': 2015, 'fp': 'FY', 'form': '10-K', 'filed': '2015-07-31'}
{'start': '2013-07-01', 'end': '2014-06-30', 'val': 175000000, 'accn': '0001193125-15-353706', 'fy': None, 'fp': None, 'form': '8-K', 'filed': '2015-10-27'}
{'start': '2013-07-01', 'end': '2014-06-30', 'val': 175000000, 'accn': '0001193125-16-662209', 'fy': 2016, 'fp': 'FY', 'form': '10-K', 'filed': '2016-07-28', 'frame': 'CY2014'}
{'start': '2014-04-01', 'end': '2014-06-30', 'val': 28000000, 'accn': '0001193125-16-662209', 'fy': 2016, 'fp': 'FY', 'form': '10-K', 'filed': '2016-07-28', 'frame': 'CY2014Q2'}
{'start': '2014-07-01', 'end': '2014-09-30', 'val': 43000000, 'accn': '0001193125-16-662209', 'fy': 2016, 'fp': 'FY', 'form': '10-K', 'filed': '2016-07-28', 'frame': 'CY2014Q3'}
{'start': '2014-10-01', 'end': '2014-12-31', 'val': 43000000, 'accn': '0001193125-16-662209', 'fy': 2016, 'fp': 'FY', 'form': '10-K', 'filed': '2016-07-28', 'frame': 'CY2014Q4'}
{'start': '2015-01-01', 'end': '2015-03-31', 'val': 116000000, 'accn': '0001193125-16-662209', 'fy': 2016, 'fp': 'FY', 'form': '10-K', 'filed': '2016-07-28', 'frame': 'CY2015Q1'}
{'start': '2014-07-01', 'end': '2015-06-30', 'val': 295000000, 'accn': '0001193125-15-272806', 'fy': 2015, 'fp': 'FY', 'form': '10-K', 'filed': '2015-07-31'}
{'start': '2014-07-01', 'end': '2015-06-30', 'val': 295000000, 'accn': '0001193125-15-353706', 'fy': None, 'fp': None, 'form': '8-K', 'filed': '2015-10-27'}
{'start': '2014-07-01', 'end': '2015-06-30', 'val': 295000000, 'accn': '0001193125-16-662209', 'fy': 2016, 'fp': 'FY', 'form': '10-K', 'filed': '2016-07-28'}
{'start': '2014-07-01', 'end': '2015-06-30', 'val': 295000000, 'accn': '0001564590-17-014900', 'fy': 2017, 'fp': 'FY', 'form': '10-K', 'filed': '2017-08-02', 'frame': 'CY2015'}
{'start': '2015-04-01', 'end': '2015-06-30', 'val': 93000000, 'accn': '0001193125-16-662209', 'fy': 2016, 'fp': 'FY', 'form': '10-K', 'filed': '2016-07-28', 'frame': 'CY2015Q2'}
{'start': '2015-07-01', 'end': '2015-09-30', 'val': 89000000, 'accn': '0001193125-16-662209', 'fy': 2016, 'fp': 'FY', 'form': '10-K', 'filed': '2016-07-28'}
{'start': '2015-07-01', 'end': '2015-09-30', 'val': 89000000, 'accn': '0001193125-16-742796', 'fy': 2017, 'fp': 'Q1', 'form': '10-Q', 'filed': '2016-10-20', 'frame': 'CY2015Q3'}
{'start': '2015-10-01', 'end': '2015-12-31', 'val': 66000000, 'accn': '0001193125-16-662209', 'fy': 2016, 'fp': 'FY', 'form': '10-K', 'filed': '2016-07-28', 'frame': 'CY2015Q4'}
{'start': '2015-07-01', 'end': '2016-03-31', 'val': 224000000, 'accn': '0001564590-17-007547', 'fy': 2017, 'fp': 'Q3', 'form': '10-Q', 'filed': '2017-04-27'}
{'start': '2016-01-01', 'end': '2016-03-31', 'val': 69000000, 'accn': '0001193125-16-662209', 'fy': 2016, 'fp': 'FY', 'form': '10-K', 'filed': '2016-07-28', 'frame': 'CY2016Q1'}
{'start': '2015-07-01', 'end': '2016-06-30', 'val': 294000000, 'accn': '0001193125-16-662209', 'fy': 2016, 'fp': 'FY', 'form': '10-K', 'filed': '2016-07-28'}
{'start': '2015-07-01', 'end': '2016-06-30', 'val': 294000000, 'accn': '0001564590-17-014900', 'fy': 2017, 'fp': 'FY', 'form': '10-K', 'filed': '2017-08-02'}
{'start': '2015-07-01', 'end': '2016-06-30', 'val': 294000000, 'accn': '0001564590-18-019062', 'fy': 2018, 'fp': 'FY', 'form': '10-K', 'filed': '2018-08-03', 'frame': 'CY2016'}
{'start': '2016-04-01', 'end': '2016-06-30', 'val': 70000000, 'accn': '0001193125-16-662209', 'fy': 2016, 'fp': 'FY', 'form': '10-K', 'filed': '2016-07-28', 'frame': 'CY2016Q2'}
{'start': '2016-07-01', 'end': '2016-09-30', 'val': 63000000, 'accn': '0001193125-16-742796', 'fy': 2017, 'fp': 'Q1', 'form': '10-Q', 'filed': '2016-10-20', 'frame': 'CY2016Q3'}
{'start': '2016-07-01', 'end': '2017-03-31', 'val': 147000000, 'accn': '0001564590-17-007547', 'fy': 2017, 'fp': 'Q3', 'form': '10-Q', 'filed': '2017-04-27'}
{'start': '2016-07-01', 'end': '2017-03-31', 'val': 147000000, 'accn': '0001564590-18-009307', 'fy': 2018, 'fp': 'Q3', 'form': '10-Q', 'filed': '2018-04-26'}
{'start': '2016-07-01', 'end': '2017-06-30', 'val': 170000000, 'accn': '0001564590-17-014900', 'fy': 2017, 'fp': 'FY', 'form': '10-K', 'filed': '2017-08-02'}
{'start': '2016-07-01', 'end': '2017-06-30', 'val': 170000000, 'accn': '0001564590-18-019062', 'fy': 2018, 'fp': 'FY', 'form': '10-K', 'filed': '2018-08-03'}
{'start': '2016-07-01', 'end': '2017-06-30', 'val': 170000000, 'accn': '0001564590-19-027952', 'fy': 2019, 'fp': 'FY', 'form': '10-K', 'filed': '2019-08-01', 'frame': 'CY2017'}
{'start': '2017-07-01', 'end': '2018-06-30', 'val': 99000000, 'accn': '0001564590-18-019062', 'fy': 2018, 'fp': 'FY', 'form': '10-K', 'filed': '2018-08-03'}
{'start': '2017-07-01', 'end': '2018-06-30', 'val': 99000000, 'accn': '0001564590-19-027952', 'fy': 2019, 'fp': 'FY', 'form': '10-K', 'filed': '2019-08-01'}
{'start': '2017-07-01', 'end': '2018-06-30', 'val': 99000000, 'accn': '0001564590-20-034944', 'fy': 2020, 'fp': 'FY', 'form': '10-K', 'filed': '2020-07-30', 'frame': 'CY2018'}
{'start': '2018-07-01', 'end': '2019-06-30', 'val': 150000000, 'accn': '0001564590-19-027952', 'fy': 2019, 'fp': 'FY', 'form': '10-K', 'filed': '2019-08-01'}
{'start': '2018-07-01', 'end': '2019-06-30', 'val': 150000000, 'accn': '0001564590-20-034944', 'fy': 2020, 'fp': 'FY', 'form': '10-K', 'filed': '2020-07-30'}
{'start': '2018-07-01', 'end': '2019-06-30', 'val': 150000000, 'accn': '0001564590-21-039151', 'fy': 2021, 'fp': 'FY', 'form': '10-K', 'filed': '2021-07-29', 'frame': 'CY2019'}
{'start': '2019-07-01', 'end': '2020-06-30', 'val': 126000000, 'accn': '0001564590-20-034944', 'fy': 2020, 'fp': 'FY', 'form': '10-K', 'filed': '2020-07-30'}
{'start': '2019-07-01', 'end': '2020-06-30', 'val': 126000000, 'accn': '0001564590-21-039151', 'fy': 2021, 'fp': 'FY', 'form': '10-K', 'filed': '2021-07-29'}
{'start': '2019-07-01', 'end': '2020-06-30', 'val': 126000000, 'accn': '0001564590-22-026876', 'fy': 2022, 'fp': 'FY', 'form': '10-K', 'filed': '2022-07-28', 'frame': 'CY2020'}
{'start': '2020-07-01', 'end': '2021-06-30', 'val': 101000000, 'accn': '0001564590-21-039151', 'fy': 2021, 'fp': 'FY', 'form': '10-K', 'filed': '2021-07-29'}
{'start': '2020-07-01', 'end': '2021-06-30', 'val': 101000000, 'accn': '0001564590-22-026876', 'fy': 2022, 'fp': 'FY', 'form': '10-K', 'filed': '2022-07-28'}
{'start': '2020-07-01', 'end': '2021-06-30', 'val': 101000000, 'accn': '0000950170-23-035122', 'fy': 2023, 'fp': 'FY', 'form': '10-K', 'filed': '2023-07-27', 'frame': 'CY2021'}